
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kvantorium_Project
{

using System;
    using System.Collections.Generic;
    
public partial class Autorization
{

    public int Id { get; set; }

    public int IdReg { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string TypeUser { get; set; }



    public virtual Registration Registration { get; set; }

}

}
