//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvantorium_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetOborud
    {
        public int Id { get; set; }
        public int IdPostav { get; set; }
        public int IdSotr { get; set; }
        public string Price { get; set; }
        public string DateVid { get; set; }
    }
}
